---
# Slurm config bwuni gpu
name: "SLURM"   # MUST BE "SLURM"
partition: "gpu_8"  # "single" for cpu, "gpu_4" or gpu_8" for gpu
job-name: "test" # this will be the experiment's name in slurm
num_parallel_jobs: 10  # max number of jobs executed in parallel
ntasks: 1   #  leave that like it is
cpus-per-task: 1   # there are 5 cores for each GPU on the gpu_8 queue and 10 per GPU on the gpu_4 queue. Never use 5! don't ask why!
time: 300   # in minutes #for one job or for all? i guess for one job
sbatch_args:   # gpus need to be explicitly requested using this
  gres: "gpu:1" #and this
---
name: "spaceTIME-lost"
path: "/home/kit/anthropomatik/fu2759/spacetime/out"
repetitions: 1 # how many hyperparameter combinations should be tried? wieso denn 5 mal amk wenn ich doch nur ein 3x3 grid angebe. macht gar keinen sinn
reps_per_job: 1 # 2 würde sequentiell die liste in einen job
reps_in_parallel: 1
params:
  wandb_project_name: spacetime-lost

  model: 'spacetime'
  embedding_config: 'embedding/repeat'
  preprocess_config: 'preprocess/default'
  encoder_config: 'encoder/default_no_skip'
  decoder_config: 'decoder/default'
  output_config: 'output/default'
  n_blocks: 1
  n_kernels: None
  n_heads: None
  model_dim: None
  input_dim: 1
  kernel_dim: 64
  activation: None
  dropout: 0.25
  layernorm: None
  norm_order: 1
  kernel_init: None
  skip_ssm: None
  mlp_n_layers: None
  mlp_n_activations: None
  mlp_preactivation: None
  skip_mlp: None
  dataset: 'robot'
  dataset_type: ''
  variant: None
  trainer: 'default'
  loader: 'default'
  num_workers: 2
  data_dir: './data'
  features: 'M'
  no_scale: False
  inverse: False
  data_transform: 'none'
  lag: 150
  horizon: 750
  loss: 'informer_rmse'
  criterion_weights: ['1' '1' '1']
  optimizer: 'adamw'
  scheduler: 'timm_cosine'
  batch_size: 50
  max_epochs: 1
  early_stopping_epochs: 1
  val_metric: 'informer_rmse'
  lr: 0.001
  weight_decay: 0.0001
  momentum: 0.0
  log_epoch: 10
  no_wandb: False
  wandb_entity: 'jannik-bach'
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  no_cuda: False
  no_pin_memory: False
  verbose: False
  replicate: 0
  seed: 0
