max_epochs: 200
early_stopping_epochs: 10
dataset: robot
dataset_type: informer
lag: 150
features: M
embedding_config: embedding/repeat
encoder_config: encoder/default_no_skip
decoder_config: decoder/default
output_config: output/default
n_blocks: 1
kernel_dim: 64
norm_order: 1
batch_size: 50
dropout: 0.25
lr: 0.001
weight_decay: 0.0001
loss: rmse
val_metric: informer_rmse
criterion_weights: [1, 1, 1]
seed: 0
data_transform: none
wandb_project_name: etth_cluster-spacetime
model: spacetime
preprocess_config: preprocess/default
n_kernels: None
n_heads: None
model_dim: None
input_dim: 1
activation: gelu
layernorm: None
kernel_init: None
skip_ssm: None
mlp_n_layers: None
mlp_n_activations: None
mlp_preactivation: None
skip_mlp: None
variant: 1
trainer: default
loader: default
num_workers: 2
data_dir: './data'
no_scale: False
inverse: False
optimizer: adamw
scheduler: timm_cosine
momentum: 0.0

# Saving + logging
log_epoch: 10
no_wandb: False
wandb_entity: 'jannik-bach'
log_dir: './logs'
checkpoint_dir: './checkpoints'
no_cuda: False
no_pin_memory: False
verbose: False
replicate: 0
horizon: 750
